### ISSUE TITLE
Java version dependency issue

### ISSUE THREAD

**Issue by ebbnormal** [Swagger2Markup/swagger2markup-cli#13]
I am running the sagger2markup-cli with ascii-doctor. I do the following at my command lind: 

`. buildDocs.sh`

And i get the following error thrown in my swagger .jar file. 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/swagger2markup/cli/Application : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

I am using `swagger2markup-cli-1.0.0.jar` version of the JAR.

**Comment by ebbnormal** [comment]
i needed to update my JDK.
