### ISSUE TITLE
Build failure on debian 9.9 (stretch)

### ISSUE THREAD

**Issue by KantarBruceAdams** [Swagger2Markup/swagger2markup-cli#27]
I am able to build swagger2markup but swagger2markup-cli on my Debian installation.

Environment
-----------------

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
$ uname -a
Linux mymachine 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Debian-1bpo92)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Debian-1bpo92, mixed mode, sharing)

----

First I tried using gradlew

swagger2markup-cli$ ./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.3'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
brucea@rtm-vod-tests:~/work/git/swagger2markup-cli$ ./gradlew --stacktrace --info --debug
11:02:25.781 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /home/brucea/.gradle/native
11:02:25.837 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:02:25.838 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:02:25.838 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:02:25.839 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:02:25.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not determine java version from '11.0.3'.
11:02:25.842 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:02:25.843 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
11:02:25.844 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.IllegalArgumentException: Could not determine java version from '11.0.3'.
11:02:25.845 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
11:02:25.845 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
11:02:25.845 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:42)
11:02:25.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
11:02:25.846 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
11:02:25.847 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
11:02:25.847 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
11:02:25.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:246)
11:02:25.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
11:02:25.849 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.Main.doAction(Main.java:33)
11:02:25.849 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
11:02:25.849 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:02:25.849 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:02:25.849 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:02:25.850 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:02:25.850 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
11:02:25.850 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
11:02:25.850 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
11:02:25.850 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:02:25.850 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:02:25.851 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org

Reading around this has something do with having an old version of gradle.
So I installed the latest 6.0 using stackman (as suggested here - https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2)

I now get a different problem:

>gradle assemble --debug --info
Initialized native services in: /home/brucea/.gradle/native
The client will now receive all logging from the daemon (pid: 97196). The daemon log file: /home/brucea/.gradle/daemon/6.0/daemon-97196.out.log
Starting 5th build in daemon [uptime: 7 mins 2.186 secs, performance: 100%, non-heap usage: 19% of 268.4 MB]
Using 2 worker leases.
Starting Build
Settings evaluated using settings file '/home/brucea/work/git/swagger2markup-cli/settings.gradle'.
Projects loaded. Root project using build file '/home/brucea/work/git/swagger2markup-cli/build.gradle'.
Included projects: [root project 'swagger2markup-cli']

> Configure project :
Evaluating root project 'swagger2markup-cli' using build file '/home/brucea/work/git/swagger2markup-cli/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Script '/home/brucea/work/git/swagger2markup-cli/gradle/publishing.gradle' line: 99

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'sourcesJar' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 982ms

**Comment by KantarBruceAdams** [comment]
I found a workaround. The parent project mentions bintray which led me to:

    https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.3/

The download link has a spurious colon added for some strange reason. The actual download is here (rather than :swagger2markup-cli-1.3.3.jar):

    wget https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.3/swagger2markup-cli-1.3.3.jar

This jar seems to work. So there is a working binary installation available.
For people like me who are not used to gradle it would be useful to advertise this option on the main page.

**Comment by RobWin** [comment]
You could also use the docker container, if you don't want to install java.
