### ISSUE TITLE
Swagger 1.2 Docs not working

### ISSUE THREAD

**Issue by hamzakc** [Swagger2Markup/swagger2markup-cli#6]
HI.

I am trying to use the command line utility to generate documentation from a swagger 1.2 json file.  However it does not work.

I am getting this error:

```
java -jar build/libs/swagger2markup-cli-0.9.2.jar generate -i https://raw.githubusercontent.com/strongloop/loopback-swagger/master/example/pet-store-1.2.json -o pet-1.2 -l ASCCIDOC
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from https://raw.githubusercontent.com/strongloop/loopback-swagger/master/example/pet-store-1.2.json
reading from https://raw.githubusercontent.com/strongloop/loopback-swagger/master/example/pet-store-1.2.json
Exception in thread "main" java.lang.IllegalArgumentException: Failed to read the Swagger file.
        at io.github.robwin.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:154)
        at io.github.robwin.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:59)
        at io.github.robwin.swagger2markup.Application$Generate.run(Application.java:71)
        at io.github.robwin.swagger2markup.Application.main(Application.java:16)
```

Swagger 2 json files work fine.

Thanks
Hamza

**Comment by RobWin** [comment]
Hi can you provide me the Swagger Spec file? There seems to be a problem in the swagger-parser.

**Comment by hamzakc** [comment]
Hi 

Do you mean the swagger JSON file? If so it is here:
https://raw.githubusercontent.com/strongloop/loopback-swagger/master/example/pet-store-1.2.json

But I had problems with a few more private 1.2 json files, They are private api's, so I can't provide them. 
Can you convert a 1.2 file?

Thanks.
Hamza

**Comment by RobWin** [comment]
We use the official swagger-parser internally. If there are problems with 1.2 it must be an issue in the swagger-parser.
Swagger v2 is better supported.

**Comment by anhcuong** [comment]
I encounter the same issue today using swagger2markup-cli-0.9.2.jar

The log looks like this

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from jira-demo.yml
reading from jira-demo.yml
Exception in thread "main" java.lang.IllegalArgumentException: Failed to read the Swagger file. 
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:154)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:59)
	at io.github.robwin.swagger2markup.Application$Generate.run(Application.java:72)
	at io.github.robwin.swagger2markup.Application.main(Application.java:16)
```

**Comment by RobWin** [comment]
Better use Swagger Spec v2. V1.2 is deprecated.

**Comment by rickster13** [comment]
Doesn't work on v2.0 as well. Keep getting the same error.
